**Data description with Pandas** is about understanding the variables or features in the DataFrame.<br>
Pandas functions for creating Descriptive Statistics or making Data Descriptions simply create parametric descriptions of the variables, and we can print them as collections or tables of numbers which are useful for describing the data.

In [1]:
import pandas as pd

cardata = {"Mercedes": [2, 4, 0, 4, 0, 3],
           "Ford": [3, 0, 0, 1, 6, 12],
           "Tata": [9, 3, 4, 1, 0, 0],
           "Renault": [12, 1, 0, 0, 3, 1],
          }
carsales = pd.DataFrame(cardata)
carsales.index.rename("Sales place", inplace=True)
carsales.rename(index={0: "One",
                       1: "Two",
                       2: "Three",
                       3: "Four",
                       4: "Five",
                       5: "Six",
                      },
                inplace=True)
carsales

             Mercedes  Ford  Tata  Renault
Sales place
One                 2     3     9       12
Two                 4     0     3        1
Three               0     0     4        0
Four                4     1     1        0
Five                0     6     0        3
Six                 3    12     0        1

# `.agg()`

- make some summary data descriptors

In [2]:
carsales.agg(["sum", "max", "min"])

     Mercedes  Ford  Tata  Renault
sum        13    22    17       17
max         4    12     9       12
min         0     0     0        0

In [3]:
carsales.agg(sum=("Ford", "sum"), max=("Ford", "max"), min=("Ford", "min"))

     Ford
sum    22
max    12
min     0

- make different summary data descriptions for selected columns

In [4]:
carsales.agg({"Ford": ["sum", "max", "min"],
              "Tata": ["sum", "max", "min", "count"],
             })

       Ford  Tata
sum    22.0    17
max    12.0     9
min     0.0     0
count   NaN     6

- create aggregate statistics for columns (total number of sales per brand)

In [5]:
carsales[["Mercedes", "Ford", "Tata", "Renault"]].agg("sum")

Mercedes    13
Ford        22
Tata        17
Renault     17
dtype: int64

- create aggregate statistics for rows (mean number of sales per salesplace)

In [6]:
carsales.agg("mean", axis=1)

Sales place
One      6.50
Two      2.00
Three    1.00
Four     1.50
Five     2.25
Six      4.00
dtype: float64

# `.describe()`

This function produces a standardized output with parameters in the float format for the DataFrame.<br>
These are:
1. *count*
2. *mean*
3. *standard deviation*
4. *min*
5. *quartiles (25, median, 75)*
6. *max*

In [7]:
carsales.describe()

       Mercedes       Ford      Tata    Renault
count  6.000000   6.000000  6.000000   6.000000
mean   2.166667   3.666667  2.833333   2.833333
std    1.834848   4.676181  3.430258   4.622409
min    0.000000   0.000000  0.000000   0.000000
25%    0.500000   0.250000  0.250000   0.250000
50%    2.500000   2.000000  2.000000   1.000000
75%    3.750000   5.250000  3.750000   2.500000
max    4.000000  12.000000  9.000000  12.000000

# `.value_counts()`

- show the count of each data item. This can augment descriptive statistics.

In [8]:
carsales["Ford"].value_counts()

Ford
0     2
3     1
1     1
6     1
12    1
Name: count, dtype: int64

- **normalize** the value counts to show the % of the distribution values

In [9]:
carsales["Ford"].value_counts(normalize=True)

Ford
0     0.333333
3     0.166667
1     0.166667
6     0.166667
12    0.166667
Name: proportion, dtype: float64

- create a new column with total sales and add it to the DataFrame

In [10]:
carsales.columns

Index(['Mercedes', 'Ford', 'Tata', 'Renault'], dtype='object')

In [11]:
carsales["TotalSales"] = carsales[carsales.columns].sum(axis=1)
carsales

             Mercedes  Ford  Tata  Renault  TotalSales
Sales place
One                 2     3     9       12          26
Two                 4     0     3        1           8
Three               0     0     4        0           4
Four                4     1     1        0           6
Five                0     6     0        3           9
Six                 3    12     0        1          16

# `.apply()`

Useful to apply a Python (or any other language) function on every column entry in a DataFrame.

In [12]:
def rate_sales(sold):
    if sold >= 15:
        return "Excellent"
    elif sold >= 5:
        return "Sufficient"
    else:
        return "Insufficient"

In [13]:
carsales["SalesRating"] = carsales["TotalSales"].apply(rate_sales)
carsales

             Mercedes  Ford  Tata  Renault  TotalSales   SalesRating
Sales place
One                 2     3     9       12          26     Excellent
Two                 4     0     3        1           8    Sufficient
Three               0     0     4        0           4  Insufficient
Four                4     1     1        0           6    Sufficient
Five                0     6     0        3           9    Sufficient
Six                 3    12     0        1          16     Excellent